CREATE TABLE MESSAGE(
message_id BIGINT AUTO_INCREMENT PRIMARY KEY,
content VARCHAR(300) NOT NULL
);
CREATE TABLE GROUP_MESSAGE(
group_message_id BIGINT AUTO_INCREMENT PRIMARY KEY,
name_group VARCHAR(300) NOT NULL,
total_per_group int
);